version: "3"
services: 
  api:
    build: .
    environment: 
      - MONGOURI=mongodb://mongo/yourapp
    ports: 
      - 3000:3000
    depends_on: 
      - mongo
  
  mongo:
    image: mongo
    ports:
    - "27017:27017"